build:
	cp ../openssh-portable/sk-usbhid.c .
	cp ../openssh-portable/sk-api.h .
	cp ../openssh-portable/misc.h .
	cp ../openssh-portable/log.h .
	cp ../openssh-portable/log.c .
	cp ../openssh-portable/ssherr.h .
	cp ../openssh-portable/ssherr.h .
	cp ../openssh-portable/openbsd-compat/recallocarray.c .
	cp ../openssh-portable/openbsd-compat/freezero.c .
	cp ../openssh-portable/fatal.c .
	cp ../openssh-portable/match.{c,h} .

	touch includex.h
	# touch misc.h
	touch log.h
	touch xmalloc.h
	# touch match.h
		# -shared \
	gcc \
		-I . \
		-D ENABLE_SK_INTERNAL \
		-D WITH_OPENSSL \
		-D OPENSSL_HAS_ECC \
		-D HAVE_FIDO_CRED_SET_CLIENTDATA \
		-D HAVE_FIDO_ASSERT_SET_CLIENTDATA \
		-D HAVE_FIDO_DEV_IS_WINHELLO \
		$(shell pkg-config --cflags --libs libfido2) $(shell pkg-config --cflags --libs hidapi-libusb) $(shell pkg-config --cflags --libs libusb-1.0) -lbsd \
		sk-usbhid.c freezero.c recallocarray.c xvasprintf.c fatal.c log.c \
		main.c

