name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/termux/package-builder:latest
      options: --user 1001
    permissions:
      contents: write
    steps:
    - name: prepare termux-package build scripts
      run: |
        pwd && ls
        pwd && ls /home/builder
        cd /home/builder
        git clone --depth=1 https://github.com/termux/termux-packages.git
        pwd && ls /home/builder/termux-packages
    - name: checkout
      uses: actions/checkout@v3
      # with:
      #   # path: /home/builder/termux-packages/packages
      #   fetch-depth: 1
    - name: copy build definitions
      run: |
        pwd && ls
        pwd && ls /home/builder
        for l in $(echo libcbor libfido2 hidapi-libusb libusb termux-skp); do
          cp -r $l /home/builder/termux-packages/packages/
        done
    - name: build packages
      run: |
        pwd && ls
        pwd && ls /home/builder
        export HOME=/home/builder
        cd /home/builder/termux-packages
        ./build-package.sh termux-skp
        ls output
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          /home/builder/termux-packages/output/*.deb
